version: "3.9"

services:

############################################### database ######################################
  postgres:
    container_name: postgresql 
    image: postgres
    env_file:
      - ./.env.local
    ports:
      - 5432:5432
  ############################################### start backend ################################
  back-end:
      container_name: back-end 
      build:
        context: ./docker/.
        dockerfile: back-end.dockerfile
      volumes:
        - ./back-end:/back-end
      #  - ./images:/back-end/images
      depends_on:
        - postgres
      env_file:
        - ./.env.local
      ports:
        - 3000:3000
      networks:
        default:
          aliases:
            - back-end
  ############################################### start front-end ###############################
  front-end:
      container_name: front-end 
      build:
        context: ./docker/.
        dockerfile: front-end.dockerfile
      depends_on:
        - back-end
      env_file:
        - ./.env.local
      volumes:
        - ./front-end:/front-end
     #   - ./images:/front-end/public/images
      ports:
        - 8080:3000
      networks:
        default:
          aliases:
            - front-end
  
